const fs = require("fs");
const path = require("path");
const { capitalCase } = require("change-case");
const { name } = require("../package.json");

const defaultReadme = `
# ${capitalCase(name)}
This character sheet is for the '${capitalCase(name)}' RPG.

> **Note:** *This README file was autogenerated. Please create your own README file in 'src'.*
`;

readmePath = path.resolve("./src/README.md");
const readme = fs.existsSync(readmePath)
  ? fs.readFileSync(readmePath, "utf8")
  : defaultReadme;

module.exports = readme;
